'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Bet
    Public Property BetID As Integer
    Public Property Mark As String
    Public Property Odds As Double
    Public Property EventID As Integer

    Public Overridable Property [Event] As [Event]
    Public Overridable Property TicketItem As ICollection(Of TicketItem) = New HashSet(Of TicketItem)

End Class
