'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [Event]
    Public Property EventID As Integer
    Public Property SublistID As Integer
    Public Property Name As String
    Public Property Outcome As String
    Public Property OriginalEventID As Nullable(Of Integer)
    Public Property Time As Date

    Public Overridable Property Bet As ICollection(Of Bet) = New HashSet(Of Bet)
    Public Overridable Property Sublist As Sublist
    Public Overridable Property Event1 As ICollection(Of [Event]) = New HashSet(Of [Event])
    Public Overridable Property Event2 As [Event]

End Class
