'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TicketItem
    Public Property TicketItemID As Integer
    Public Property BetID As Integer
    Public Property TicketID As Integer
    Public Property Status As Integer

    Public Overridable Property Bet As Bet
    Public Overridable Property Ticket As Ticket

End Class
